### PR TITLE
Add mks::condensed_chart to represent templated charts

### PR DESCRIPTION
**Pull request by horenmar**
`mks::condensed_chart` computes which keys are similar enough
to be template keys. It does so by using `mks::eigen` (and thus,
if `mks::eigen` breaks, so does `mks::condensed_chart`) and
checking which keys/locks are identical after the diagonal is
removed.

It also provides an interface for querying this condensed chart
and its associated metadata.

### CODE REVIEW

**Comment by cernoch** [comment]
I like it!

Just one question: How do you handle multi-profile lock-charts?
- I've noticed the the `ch.single_profile()` is passed to `m_condensed`. However, [line 146](https://github.com/master-keying/mks/pull/28/files#diff-84ee2c51ef194532e74790bd8cb87547R146) suggests that all cells in the condensed lock-chart are either _eigen_ or _block_. Is this right?
- Ideally, I'd say that two locks (reps. keys) are groupped together, if the set of its eigen-keys (resp. eigen-locks) _and the set of blocked-keys (resp. blocked-locks)_ are equal (except for the 1 eigen-key found by the `eigen` class).
- Pragmatically, I'd suggest `assert(ch.single_profile() && 'Lock-chart must be single-profile.)`. :-) But then, `m_condensed` must be initialized as single-profile and `m_condensed.make_block` should not be called (it would have no effect, merely consume CPU time).

**Comment by horenmar** [comment]
Are multi-profile lock-charts as currently represented actually a thing? I think I can make the changes to support them relatively easily, but I wonder if they are even useful.

**Comment by cernoch** [comment]
Multi-profile lock-charts are essential. They do help, though, for two reasons:
- Some companies assign profiles manually. Multi-profile lock-charts allow us to use their lock-charts for benchmarking.
- In future I'm planning to assign profiles manually during a ”preprocess phase”. Again, we could test this feature if we had a support for multi-profile lock-charts.

My suggestion: If it takes up to 3 days of development, let's go for it.

**Comment by horenmar** [comment]
The support is in.

**Comment by horenmar** [comment]
One more round of review:

I sped up the checking by only using relevant keys and locks in `equal_given_eigen`. If this still looks good, I am going to squash it and merge it.

**Pull request merged**
